apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-python-pipeline
description: Cloud Run pipeline for Python app
serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
    - targetId: qa
      profiles: [qa]
    - targetId: prod
      profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run dev environment
run:
  location: projects/onyx-antler-459216-j6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
description: Cloud Run QA environment
run:
  location: projects/onyx-antler-459216-j6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Cloud Run prod environment
run:
  location: projects/onyx-antler-459216-j6/locations/asia-south1
